# Form implementation generated from reading ui file 'morseAnalyzer.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DialogMorseAnalyzer(object):
    def setupUi(self, DialogMorseAnalyzer):
        DialogMorseAnalyzer.setObjectName("DialogMorseAnalyzer")
        DialogMorseAnalyzer.resize(400, 300)

        self.retranslateUi(DialogMorseAnalyzer)
        QtCore.QMetaObject.connectSlotsByName(DialogMorseAnalyzer)

    def retranslateUi(self, DialogMorseAnalyzer):
        _translate = QtCore.QCoreApplication.translate
        DialogMorseAnalyzer.setWindowTitle(_translate("DialogMorseAnalyzer", "Dialog"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogMorseAnalyzer = QtWidgets.QDialog()
    ui = Ui_DialogMorseAnalyzer()
    ui.setupUi(DialogMorseAnalyzer)
    DialogMorseAnalyzer.show()
    sys.exit(app.exec())
